---
name: action

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  actions:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: 'eep.markdownlint.json'
          globs: |
            README.md
            eeps/*.md
      - name: Build html using Gruber MD
        run: |
            ./build.pl
            ## Check for warnings by build.pl
            if grep '<h2>Warnings</h2>' > /dev/null; then
                exit 1
            fi
      - name: Deploy on erlang.org
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_ERLANG_ORG_BUILD }}
        run: |
          curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/erlang/erlang-org/actions/workflows/update-gh-cache.yaml/dispatches" -d '{"ref":"master"}'
